config/routes.rb
Rails.application.routes.draw do
	root to: "pages#index"
	resources :bank_accounts, only: [:index, :show]

	namespace  :api do
		namespace :v1 do
			post "bank_accounts/new_trasaction", to: "bank_accounts#new_trasaction"
		end
	end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPES = ["withdraw", "deposit"]

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES}
  validates :transaction_number, presence: true, uniqueness: true

  before_validation :load_defaults

  def load_defaults
  	if self.new_record?
  		self.transaction_number = SecureRandom.uuid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client

  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  before_validation :load_defaults

  has_many :account_transactions

  def load_defaults
  	if self. new_record?
  		self.balance = 0.00
    end
  end

  def to_s
  	account_number
  end
end

app/models/client.rb
class Client < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :middle_name, presence: true
	validates :client_numer, presence: true, uniqueness: true

	has_many :bank_accounts

	before_save :format_name

	def format_name
		self.first_name  = self.first_name.upcase
		self.last_name   = self.last_name.upcase
		self.middle_name = self.middle_name.upcase


	end

	def to_s
		"#{last_name}, #{first_name} #{middle_name}"
	end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class  BankAccountsController < ApplicationController
      def new_trasaction
        amount            = params[:amount]
        transaction_type  = params[:transaction_type]
        bank_account_id   = params[:bank_account_id]

        errors = ::BankAccounts::ValidateNewTransaction.new(
                    amount: amount,
                    transaction_type: transaction_type,
                    bank_account_id: bank_account_id
                  ).execute!
         if errors.size > 0
           render json: {errors: errors }, status: 402
         else
           bank_account = ::BankAccounts::PerformTransaction.new(
                             amount: amount,
                             transaction_type: transaction_type,
                             bank_account_id: bank_account_id
                          ).execute!
           render json:{ balance: bank_account.balance}
         end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
	def index
	  @bank_accounts = BankAccount.all
	end

	def show
	  @bank_account = BankAccount.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def number_of_accounts
		BankAccount.count
	end

	def number_of_clients
		Client.count
	end
end

app/views/bank_accounts/_modal_transaction.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
              %span.sr-only Close
              %h4.modal-title
                Nueva Transaccion
    .modal-body
      .row
        .col-md-12
          .notification
      .row
        .col-md-6
          %label
            Amount
          = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
        .col-md-6
          %label
            Tipo de transaccion
          = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control"
    .modal-footer
      %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
      %button#btn-save.btn.btn-primary{type:'button'} Save

app/views/bank_accounts/_transactions.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Dia de Transaccion
      %th Tipo de Transaccion
      %th Monto
  %tbody
    - bank_account.account_transactions.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transaction_type}
        %td #{number_to_currency(t.amount, unit: "P")}
    %tr
      %th
      %th Balance
      %th #{number_to_currency(bank_account.balance, unit: "P")}

app/views/bank_accounts/index.html.haml
%h1
  Cuentas Bancarias

%table.table.table-bordered
  %thead
    %tr
      %th Numero de Cuenta
      %th Balance
      %th Acciones
  %tbody
    - @bank_accounts.each do |bank_account|
      %tr
        %td #{bank_account.account_number}
        %td #{number_to_currency(bank_account.balance, unit: "P")}
        %td
          = link_to bank_account_path(bank_account.id), class: "btn btn-primary" do
            Show

app/views/bank_accounts/show.html.haml
%h1
  Numero de Cuenta: #{@bank_account.account_number}
  %small
    #{@bank_account.client}

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
  New Transaction

= render partial: "transactions", locals: { bank_account: @bank_account}
= render partial: "modal_transaction"
#parameters{ data: { bank_account_id: @bank_account.id} }

= javascript_include_tag "bank_accounts/Show"
:javascript
  $(document).ready(function() {
    Show.init();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.haml
%h1
  Mi Banco

.row
  .col-md-12
    %h2
      Numero de Cuentas: #{number_of_accounts}
    %h2
      Numero de Clientes: #{number_of_clients}

.row
  .col-md-12
    = link_to bank_accounts_path do
      Bank Accounts




